FROM golang:latest AS builder

WORKDIR /app
COPY ./go.mod ./go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o server ./main.go

FROM scratch
WORKDIR /
COPY --from=builder /app/server .
COPY ./config/config.toml /config/config.toml
EXPOSE 1323
CMD ["./server"]
